/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentsNewRouteImport } from './routes/shipments.new'
import { Route as ShipmentsIdRouteImport } from './routes/shipments.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as CustomersNewRouteImport } from './routes/customers.new'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsNewRoute = ShipmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShipmentsRoute,
} as any)
const ShipmentsIdRoute = ShipmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShipmentsRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/users': typeof UsersRoute
  '/customers/new': typeof CustomersNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/new': typeof ShipmentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/users': typeof UsersRoute
  '/customers/new': typeof CustomersNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/new': typeof ShipmentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/users': typeof UsersRoute
  '/customers/new': typeof CustomersNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/new': typeof ShipmentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/invoices'
    | '/login'
    | '/shipments'
    | '/users'
    | '/customers/new'
    | '/invoices/new'
    | '/shipments/$id'
    | '/shipments/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/invoices'
    | '/login'
    | '/shipments'
    | '/users'
    | '/customers/new'
    | '/invoices/new'
    | '/shipments/$id'
    | '/shipments/new'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/invoices'
    | '/login'
    | '/shipments'
    | '/users'
    | '/customers/new'
    | '/invoices/new'
    | '/shipments/$id'
    | '/shipments/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShipmentsRoute: typeof ShipmentsRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/new': {
      id: '/shipments/new'
      path: '/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof ShipmentsNewRouteImport
      parentRoute: typeof ShipmentsRoute
    }
    '/shipments/$id': {
      id: '/shipments/$id'
      path: '/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof ShipmentsIdRouteImport
      parentRoute: typeof ShipmentsRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesNewRoute: typeof InvoicesNewRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesNewRoute: InvoicesNewRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface ShipmentsRouteChildren {
  ShipmentsIdRoute: typeof ShipmentsIdRoute
  ShipmentsNewRoute: typeof ShipmentsNewRoute
}

const ShipmentsRouteChildren: ShipmentsRouteChildren = {
  ShipmentsIdRoute: ShipmentsIdRoute,
  ShipmentsNewRoute: ShipmentsNewRoute,
}

const ShipmentsRouteWithChildren = ShipmentsRoute._addFileChildren(
  ShipmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  ShipmentsRoute: ShipmentsRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
