/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SuppliersNewRouteImport } from './routes/suppliers.new'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as ShipmentsNewRouteImport } from './routes/shipments.new'
import { Route as ShipmentsIdRouteImport } from './routes/shipments.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as ExpensesIdRouteImport } from './routes/expenses.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ShipmentsIdIndexRouteImport } from './routes/shipments.$id.index'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as SuppliersIdEditRouteImport } from './routes/suppliers.$id.edit'
import { Route as ShipmentsIdEditRouteImport } from './routes/shipments.$id.edit'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliersRoute,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShipmentsRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const SuppliersNewRoute = SuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const ShipmentsNewRoute = ShipmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShipmentsRoute,
} as any)
const ShipmentsIdRoute = ShipmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShipmentsRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const ExpensesIdRoute = ExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const ShipmentsIdIndexRoute = ShipmentsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShipmentsIdRoute,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersIdRoute,
} as any)
const SuppliersIdEditRoute = SuppliersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SuppliersIdRoute,
} as any)
const ShipmentsIdEditRoute = ShipmentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ShipmentsIdRoute,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/catalog': typeof CatalogRoute
  '/customers': typeof CustomersRouteWithChildren
  '/docs': typeof DocsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/shipments/$id': typeof ShipmentsIdRouteWithChildren
  '/shipments/new': typeof ShipmentsNewRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/shipments/$id/edit': typeof ShipmentsIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
  '/shipments/$id/': typeof ShipmentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/catalog': typeof CatalogRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/customers/new': typeof CustomersNewRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/shipments/new': typeof ShipmentsNewRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/shipments/$id/edit': typeof ShipmentsIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
  '/customers/$id': typeof CustomersIdIndexRoute
  '/shipments/$id': typeof ShipmentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/catalog': typeof CatalogRoute
  '/customers': typeof CustomersRouteWithChildren
  '/docs': typeof DocsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/shipments/$id': typeof ShipmentsIdRouteWithChildren
  '/shipments/new': typeof ShipmentsNewRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/shipments/$id/edit': typeof ShipmentsIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
  '/shipments/$id/': typeof ShipmentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/catalog'
    | '/customers'
    | '/docs'
    | '/invoices'
    | '/login'
    | '/profile'
    | '/purchases'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/users'
    | '/customers/$id'
    | '/customers/new'
    | '/expenses/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/shipments/$id'
    | '/shipments/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/invoices/'
    | '/shipments/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/shipments/$id/edit'
    | '/suppliers/$id/edit'
    | '/customers/$id/'
    | '/shipments/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/catalog'
    | '/docs'
    | '/login'
    | '/profile'
    | '/purchases'
    | '/settings'
    | '/users'
    | '/customers/new'
    | '/expenses/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/shipments/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers'
    | '/invoices'
    | '/shipments'
    | '/suppliers'
    | '/customers/$id/edit'
    | '/shipments/$id/edit'
    | '/suppliers/$id/edit'
    | '/customers/$id'
    | '/shipments/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/catalog'
    | '/customers'
    | '/docs'
    | '/invoices'
    | '/login'
    | '/profile'
    | '/purchases'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/users'
    | '/customers/$id'
    | '/customers/new'
    | '/expenses/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/shipments/$id'
    | '/shipments/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/invoices/'
    | '/shipments/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/shipments/$id/edit'
    | '/suppliers/$id/edit'
    | '/customers/$id/'
    | '/shipments/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CatalogRoute: typeof CatalogRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DocsRoute: typeof DocsRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UsersRoute: typeof UsersRoute
  ExpensesIdRoute: typeof ExpensesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof ShipmentsRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/suppliers/new': {
      id: '/suppliers/new'
      path: '/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof SuppliersNewRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/shipments/new': {
      id: '/shipments/new'
      path: '/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof ShipmentsNewRouteImport
      parentRoute: typeof ShipmentsRoute
    }
    '/shipments/$id': {
      id: '/shipments/$id'
      path: '/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof ShipmentsIdRouteImport
      parentRoute: typeof ShipmentsRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/expenses/$id': {
      id: '/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof ExpensesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/shipments/$id/': {
      id: '/shipments/$id/'
      path: '/'
      fullPath: '/shipments/$id/'
      preLoaderRoute: typeof ShipmentsIdIndexRouteImport
      parentRoute: typeof ShipmentsIdRoute
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/suppliers/$id/edit': {
      id: '/suppliers/$id/edit'
      path: '/edit'
      fullPath: '/suppliers/$id/edit'
      preLoaderRoute: typeof SuppliersIdEditRouteImport
      parentRoute: typeof SuppliersIdRoute
    }
    '/shipments/$id/edit': {
      id: '/shipments/$id/edit'
      path: '/edit'
      fullPath: '/shipments/$id/edit'
      preLoaderRoute: typeof ShipmentsIdEditRouteImport
      parentRoute: typeof ShipmentsIdRoute
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface ShipmentsIdRouteChildren {
  ShipmentsIdEditRoute: typeof ShipmentsIdEditRoute
  ShipmentsIdIndexRoute: typeof ShipmentsIdIndexRoute
}

const ShipmentsIdRouteChildren: ShipmentsIdRouteChildren = {
  ShipmentsIdEditRoute: ShipmentsIdEditRoute,
  ShipmentsIdIndexRoute: ShipmentsIdIndexRoute,
}

const ShipmentsIdRouteWithChildren = ShipmentsIdRoute._addFileChildren(
  ShipmentsIdRouteChildren,
)

interface ShipmentsRouteChildren {
  ShipmentsIdRoute: typeof ShipmentsIdRouteWithChildren
  ShipmentsNewRoute: typeof ShipmentsNewRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
}

const ShipmentsRouteChildren: ShipmentsRouteChildren = {
  ShipmentsIdRoute: ShipmentsIdRouteWithChildren,
  ShipmentsNewRoute: ShipmentsNewRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
}

const ShipmentsRouteWithChildren = ShipmentsRoute._addFileChildren(
  ShipmentsRouteChildren,
)

interface SuppliersIdRouteChildren {
  SuppliersIdEditRoute: typeof SuppliersIdEditRoute
}

const SuppliersIdRouteChildren: SuppliersIdRouteChildren = {
  SuppliersIdEditRoute: SuppliersIdEditRoute,
}

const SuppliersIdRouteWithChildren = SuppliersIdRoute._addFileChildren(
  SuppliersIdRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRouteWithChildren
  SuppliersNewRoute: typeof SuppliersNewRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRouteWithChildren,
  SuppliersNewRoute: SuppliersNewRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CatalogRoute: CatalogRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DocsRoute: DocsRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  UsersRoute: UsersRoute,
  ExpensesIdRoute: ExpensesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
